// Border Radius
const BORDER_RADIUS_EXTRA_SMALL = 2;
const BORDER_RADIUS_SMALL = 4;
const BORDER_RADIUS_MEDIUM = 6;
const BORDER_RADIUS_LARGE = 10;
const BORDER_RADIUS_EXTRA_LARGE = 12;
const BORDER_RADIUS_EXTRA_EXTRA_LARGE = 16;

export const radius = {
  xs: BORDER_RADIUS_EXTRA_SMALL,
  sm: BORDER_RADIUS_SMALL,
  md: BORDER_RADIUS_MEDIUM,
  lg: BORDER_RADIUS_LARGE,
  xl: BORDER_RADIUS_EXTRA_LARGE,
  '2xl': BORDER_RADIUS_EXTRA_EXTRA_LARGE,
};
